"""create vacancy table

Revision ID: 0d6d6756679c
Revises: 8d5facbe7a81
Create Date: 2026-02-17 00:49:25.275152

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d6d6756679c"
down_revision: Union[str, Sequence[str], None] = "8d5facbe7a81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacancy",
        sa.Column("vacancy_id", sa.UUID(), nullable=False),
        sa.Column("vacancy_name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("vacancy_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vacancy")
    # ### end Alembic commands ###
