"""init

Revision ID: 6795fa821737
Revises:
Create Date: 2026-02-17 21:18:05.387415

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6795fa821737"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("user_name", sa.String(length=50), nullable=True),
        sa.Column("user_first_name", sa.String(length=50), nullable=True),
        sa.Column("user_last_name", sa.String(length=50), nullable=True),
        sa.Column("user_language", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "vacancy",
        sa.Column("vacancy_id", sa.String(length=36), nullable=False),
        sa.Column("vacancy_name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("vacancy_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vacancy")
    op.drop_table("user")
    # ### end Alembic commands ###
