"""vacancy to job

Revision ID: 70eba2966794
Revises: 6795fa821737
Create Date: 2026-02-18 18:52:10.909250

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70eba2966794"
down_revision: Union[str, Sequence[str], None] = "6795fa821737"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("job_name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.drop_table("vacancy")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacancy",
        sa.Column("vacancy_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("vacancy_name", sa.VARCHAR(length=50), nullable=True),
        sa.PrimaryKeyConstraint("vacancy_id"),
    )
    op.drop_table("job")
    # ### end Alembic commands ###
