"""job model

Revision ID: 7f5e67f1f5d3
Revises:
Create Date: 2026-02-18 23:51:45.717932

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f5e67f1f5d3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("job_name", sa.String(length=100), nullable=False),
        sa.Column("job_location", sa.String(length=50), nullable=True),
        sa.Column("job_salary", sa.String(length=50), nullable=True),
        sa.Column("job_source", sa.String(length=50), nullable=True),
        sa.Column("job_type", sa.String(length=50), nullable=True),
        sa.Column("job_link", sa.String(length=250), nullable=True),
        sa.Column("job_company", sa.String(length=100), nullable=True),
        sa.Column("job_updated", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "user",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("user_name", sa.String(length=50), nullable=True),
        sa.Column("user_first_name", sa.String(length=50), nullable=True),
        sa.Column("user_last_name", sa.String(length=50), nullable=True),
        sa.Column("user_language", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("job")
    # ### end Alembic commands ###
