"""job model new fields

Revision ID: a70e95b30444
Revises: ebcc29d23dc3
Create Date: 2026-03-03 20:53:59.522529

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a70e95b30444"
down_revision: Union[str, Sequence[str], None] = "ebcc29d23dc3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job", sa.Column("job_title", sa.String(length=100), nullable=True))
    op.add_column("job", sa.Column("job_snippet", sa.String(length=500), nullable=True))
    op.drop_column("job", "job_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job", sa.Column("job_name", sa.VARCHAR(length=100), nullable=False))
    op.drop_column("job", "job_snippet")
    op.drop_column("job", "job_title")
    # ### end Alembic commands ###
