"""user_job

Revision ID: ebcc29d23dc3
Revises: 7f5e67f1f5d3
Create Date: 2026-02-25 17:08:07.651536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebcc29d23dc3"
down_revision: Union[str, Sequence[str], None] = "7f5e67f1f5d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_job",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("user_job_status", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "job_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_job")
    # ### end Alembic commands ###
