MSG_NO_JOBS_FOUND = "No jobs found."
MSG_JOB_NOT_FOUND = "Job not found or invalid request."
MSG_SESSION_EXPIRED = "Session expired. Please search again."
MSG_ENTER_KEYWORDS = "Enter keywords (example: python backend):"
MSG_ENTER_LOCATION = "Enter location (example: Remote, USA, Germany):"
